version: "3.0"

networks:
  mongo-sync:

services:
  mongo:
    hostname: "mongo"
    container_name: "mongo"
    image: "mongo:4.2"
    restart: "on-failure"
    command: ["-f", "/etc/mongod.conf", "--replSet", "rs0", "--bind_ip_all"]
    expose:
      - 27017
    ports:
      - 27020:27017
    volumes:
      - ./.mongo/data:/data/db
      - ./.mongo/log:/var/log/mongodb
      - ./.mongo/init/:/docker-entrypoint-initdb.d/
      - ./.mongo/mongod.conf:/etc/mongod.conf
    healthcheck:
      test: test $$(echo "rs.status().ok" | mongo --quiet) -eq 1
      interval: 30s
      start_period: 60s
    networks:
      - mongo-sync

  app:
    hostname: "app"
    container_name: "app"
    build:
      context: ./app
    restart: "on-failure"
    environment:
      - DB_URI=mongodb://mongo:27017
      - PORT=3030
    ports:
      - 3030:3030
    depends_on:
      - mongo
    networks:
      - mongo-sync

  streamer:
    hostname: "streamer"
    container_name: "streamer"
    build:
      context: ./streamer
    restart: "on-failure"
    environment: 
      - DB_URI=mongodb://mongo:27017
    depends_on:
      - mongo
    networks:
      - mongo-sync
